/* eslint-disable */
// This file is automatically generated, do not edit!

/**
 * @module
 * Contains type declarations for Cookware lexicons
 */

import "@atcute/client/lexicons";

declare module "@atcute/client/lexicons" {
  namespace MoeHaydenCookwareDefs {
    interface Ingredient {
      [Brand.Type]?: "moe.hayden.cookware.defs#ingredient";
      /** How much of the ingredient is needed. */
      amount?: number;
      /**
       * The name of the ingredient. \
       * Maximum string length: 3000 \
       * Maximum grapheme length: 300
       */
      name?: string;
      /**
       * The unit the ingredient is measured in. \
       * Maximum string length: 3000 \
       * Maximum grapheme length: 300
       */
      unit?: string;
    }
    interface Step {
      [Brand.Type]?: "moe.hayden.cookware.defs#step";
      /**
       * The instruction to provide to the user. \
       * Maximum string length: 5000 \
       * Maximum grapheme length: 300
       */
      text: string;
    }
  }

  /** Gets a recipe from the index by author DID and rkey. */
  namespace MoeHaydenCookwareGetRecipe {
    interface Params {
      did: string;
      rkey: string;
    }
    type Input = undefined;
    interface Output {
      recipe: Result;
    }
    interface AuthorInfo {
      [Brand.Type]?: "moe.hayden.cookware.getRecipe#authorInfo";
      handle: string;
    }
    interface Result {
      [Brand.Type]?: "moe.hayden.cookware.getRecipe#result";
      author: AuthorInfo;
      ingredients: MoeHaydenCookwareDefs.Ingredient[];
      steps: MoeHaydenCookwareDefs.Step[];
      title: string;
      description?: string;
    }
  }

  /** Gets recipes from the index. */
  namespace MoeHaydenCookwareGetRecipes {
    interface Params {
      cursor: string;
      did?: string;
    }
    type Input = undefined;
    interface Output {
      recipes: Result[];
    }
    interface Result {
      [Brand.Type]?: "moe.hayden.cookware.getRecipes#result";
      author: string;
      did: string;
      ingredients: number;
      rkey: string;
      steps: number;
      title: string;
      description?: string;
      type?: string;
    }
  }

  namespace MoeHaydenCookwareRecipe {
    /** Record containing a Cookware recipe. */
    interface Record {
      $type: "moe.hayden.cookware.recipe";
      ingredients: MoeHaydenCookwareDefs.Ingredient[];
      steps: MoeHaydenCookwareDefs.Step[];
      /**
       * The title of the recipe. \
       * Maximum string length: 3000 \
       * Maximum grapheme length: 300
       */
      title: string;
      /**
       * The description of the recipe. \
       * Maximum string length: 3000 \
       * Maximum grapheme length: 300
       */
      description?: string;
    }
  }

  interface Records {
    "moe.hayden.cookware.recipe": MoeHaydenCookwareRecipe.Record;
  }

  interface Queries {
    "moe.hayden.cookware.getRecipe": {
      params: MoeHaydenCookwareGetRecipe.Params;
      output: MoeHaydenCookwareGetRecipe.Output;
    };
    "moe.hayden.cookware.getRecipes": {
      params: MoeHaydenCookwareGetRecipes.Params;
      output: MoeHaydenCookwareGetRecipes.Output;
    };
  }

  interface Procedures {}
}
